// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 MusiThang <viktor.laszlo92@protonmail.com>

//! Who an address block is registered to: the IEEE Registration Authority's
//! public listing, as a dated snapshot compiled into the binary.
//!
//! **Registered to, not made by.** The listing names whoever bought the block.
//! A radio module carries its maker's block inside other brands' products, so
//! this answers "whose block is this" and never "who built this device", and
//! everything that shows it says so (POLICY rule 5: the label names what was
//! actually looked up). A random BLE address has no block at all and is never
//! looked up here (`signal::ble::address::kind`).
//!
//! **Longest prefix first, or thousands of answers are wrong.** The listing has
//! three block sizes: MA-L (24 bits), MA-M (28) and MA-S and the older IAB (36).
//! 6,464 of the 6,592 MA-M blocks, and the MA-S and IAB blocks, sit inside MA-L
//! blocks registered to "IEEE Registration Authority" itself, so a lookup that
//! stops at 24 bits names the registry for all of them. [`registrant`] tries 36,
//! then 28, then 24.
//!
//! **What the listing says, kept as it says it.** Two MA-L blocks are listed
//! under more than one organisation (`08:00:30` under three); the lookup
//! returns every name rather than choosing one (rule 2). Blocks whose holder
//! pays to hide the name are listed as `Private` and come back as
//! [`Registrant::Private`], a fact about the block rather than a missing one.
//! Names are the registry's with its whitespace normalised: 47 of them carry a
//! tab or a line break inside, and 690 have spaces at an end.
//!
//! **Dated, because all testimony is** (rule 4). [`fetched`] is the day the
//! snapshot was taken, and anything that shows a name can show it. The snapshot
//! is regenerated by `packaging/update-oui.sh`, which downloads the four
//! listings and runs `regenerate_the_oui_snapshot` below, so the file in the
//! tree is always the output of this module's own parser and never an edit by
//! hand (rule 7). The listing's terms, and why it is embedded, are in
//! `dev_docs/net-ux-polish-plan.md` Stop 1.6.d.

use std::sync::OnceLock;

/// The snapshot: a `#` header, then `PREFIX<TAB>NAME` rows, the prefix in hex
/// digits: 6 for a 24-bit block, 7 for 28, 9 for 36.
const SNAPSHOT: &str = include_str!("ieee_oui.tsv");

/// What the listing says about the block an address falls in.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Registrant {
    /// The block's registrant, usually one name; more only where the listing
    /// itself gives more than one for the same block.
    Listed(Vec<&'static str>),
    /// The holder paid to keep the name out of the public listing.
    Private,
    /// No block in the snapshot covers the address: unassigned, or assigned
    /// since [`fetched`].
    NotListed,
}

/// The block sizes, longest first, which is the order a lookup must try them.
const WIDTHS: [u32; 3] = [36, 28, 24];

struct Table {
    /// One sorted list per entry of [`WIDTHS`]: the block's prefix as an
    /// integer, and the row's name.
    blocks: [Vec<(u64, &'static str)>; 3],
    fetched: &'static str,
}

fn table() -> &'static Table {
    static TABLE: OnceLock<Table> = OnceLock::new();
    TABLE.get_or_init(|| parse(SNAPSHOT))
}

fn parse(text: &'static str) -> Table {
    let mut blocks: [Vec<(u64, &'static str)>; 3] = Default::default();
    let mut fetched = "";
    for line in text.lines() {
        if let Some(rest) = line.strip_prefix("# fetched ") {
            fetched = rest.trim();
            continue;
        }
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        let Some((prefix, name)) = line.split_once('\t') else {
            continue;
        };
        let Ok(value) = u64::from_str_radix(prefix, 16) else {
            continue;
        };
        let bits = prefix.len() as u32 * 4;
        if let Some(i) = WIDTHS.iter().position(|w| *w == bits) {
            blocks[i].push((value, name));
        }
    }
    for list in &mut blocks {
        // Stable, so names listed under one block keep the listing's order.
        list.sort_by_key(|(prefix, _)| *prefix);
    }
    Table { blocks, fetched }
}

/// The day the snapshot was taken from the IEEE's listing, `YYYY-MM-DD`.
#[allow(dead_code)] // shown beside the names by the address display (1.6.d, d2)
pub fn fetched() -> &'static str {
    table().fetched
}

/// Who the block holding `addr` is registered to. `addr` is in the written
/// octet order (`signal::ble::pdu::air_octets`).
#[allow(dead_code)] // called by the address display (net-ux-polish-plan 1.6.d, d2)
pub fn registrant(addr: [u8; 6]) -> Registrant {
    let whole = addr.iter().fold(0u64, |acc, b| acc << 8 | *b as u64);
    let t = table();
    for (i, bits) in WIDTHS.iter().enumerate() {
        let key = whole >> (48 - bits);
        let list = &t.blocks[i];
        let start = list.partition_point(|(p, _)| *p < key);
        let names: Vec<&'static str> = list[start..]
            .iter()
            .take_while(|(p, _)| *p == key)
            .map(|(_, n)| *n)
            .collect();
        match names.as_slice() {
            [] => continue,
            ["Private"] => return Registrant::Private,
            _ => return Registrant::Listed(names),
        }
    }
    Registrant::NotListed
}

/// The records of a CSV file as the IEEE writes them: comma-separated, a field
/// in double quotes when it holds a comma, a doubled quote inside one. Quoted
/// fields may run across lines. For the generator only; the snapshot itself is
/// tab-separated and needs none of this.
#[cfg(test)]
fn csv_records(text: &str) -> Vec<Vec<String>> {
    let mut records = Vec::new();
    let mut record = Vec::new();
    let mut field = String::new();
    let mut quoted = false;
    let mut chars = text.chars().peekable();
    while let Some(c) = chars.next() {
        match (quoted, c) {
            (true, '"') if chars.peek() == Some(&'"') => {
                field.push('"');
                chars.next();
            }
            (true, '"') => quoted = false,
            (true, c) => field.push(c),
            (false, '"') => quoted = true,
            (false, ',') => record.push(std::mem::take(&mut field)),
            (false, '\r') => {}
            (false, '\n') => {
                record.push(std::mem::take(&mut field));
                records.push(std::mem::take(&mut record));
            }
            (false, c) => field.push(c),
        }
    }
    if !field.is_empty() || !record.is_empty() {
        record.push(field);
        records.push(record);
    }
    records
}

/// A registry name as the snapshot keeps it: every run of whitespace, tabs and
/// line breaks included, folded to one space, and the ends trimmed.
#[cfg(test)]
fn normalise(name: &str) -> String {
    name.split_whitespace().collect::<Vec<_>>().join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The listings the snapshot is built from, with the registry name each
    /// file's rows carry.
    const SOURCES: [(&str, &str); 4] = [
        ("oui.csv", "MA-L"),
        ("mam.csv", "MA-M"),
        ("oui36.csv", "MA-S"),
        ("iab.csv", "IAB"),
    ];

    /// **The generator.** Run by `packaging/update-oui.sh`, never by hand and
    /// never in CI: it reads the four listings the script downloaded into
    /// `SDRTOP_IEEE_DIR`, with the script's `SHA256SUMS` and `FETCHED` beside
    /// them, and rewrites `ieee_oui.tsv`.
    #[test]
    #[ignore = "regenerates the snapshot; run through packaging/update-oui.sh"]
    fn regenerate_the_oui_snapshot() {
        let dir = std::path::PathBuf::from(
            std::env::var("SDRTOP_IEEE_DIR").expect("SDRTOP_IEEE_DIR names the download"),
        );
        let read =
            |f: &str| std::fs::read_to_string(dir.join(f)).unwrap_or_else(|e| panic!("{f}: {e}"));
        let fetched = read("FETCHED").trim().to_string();
        let sums = read("SHA256SUMS");

        let mut header = vec![
            "# IEEE Registration Authority public listing, as sdrtop's".to_string(),
            "# signal::net::vendor reads it. Generated by packaging/update-oui.sh;".to_string(),
            "# do not edit by hand. PREFIX<TAB>NAME, the prefix 6, 7 or 9 hex".to_string(),
            "# digits for a 24, 28 or 36-bit block.".to_string(),
            format!("# fetched {fetched}"),
        ];
        let mut rows: Vec<(String, String)> = Vec::new();
        for (file, registry) in SOURCES {
            let text = read(file);
            let records = csv_records(&text);
            assert_eq!(
                records.first().map(|r| r[..3].join(",")),
                Some("Registry,Assignment,Organization Name".to_string()),
                "{file}: not the IEEE's layout"
            );
            let mut count = 0;
            for r in &records[1..] {
                if r.len() < 3 {
                    continue;
                }
                assert_eq!(r[0], registry, "{file}: a row from another registry");
                assert!(
                    r[1].chars().all(|c| c.is_ascii_hexdigit()),
                    "{file}: {:?}",
                    r[1]
                );
                rows.push((r[1].to_ascii_uppercase(), normalise(&r[2])));
                count += 1;
            }
            let sha = sums
                .lines()
                .find(|l| l.ends_with(file))
                .and_then(|l| l.split_whitespace().next())
                .unwrap_or_else(|| panic!("{file}: no checksum"));
            header.push(format!(
                "# source https://standards-oui.ieee.org/ {registry} {file} rows {count} sha256 {sha}"
            ));
        }
        rows.sort_by(|a, b| (a.0.len(), &a.0).cmp(&(b.0.len(), &b.0)));

        let mut out = header.join("\n");
        out.push('\n');
        for (prefix, name) in rows {
            out.push_str(&format!("{prefix}\t{name}\n"));
        }
        let path =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src/signal/net/ieee_oui.tsv");
        std::fs::write(&path, out).unwrap();
    }

    /// The generator's CSV reading, on the shapes the IEEE's files contain:
    /// a quoted name with a comma, a doubled quote, a line break inside
    /// quotes, and a trailing record with no final newline.
    #[test]
    fn the_csv_reader_reads_what_the_ieee_writes() {
        let text = "Registry,Assignment,Organization Name,Organization Address\n\
                    MA-L,A483E7,\"Apple, Inc.\",1 Infinite Loop\n\
                    MA-L,000001,\"The \"\"Quoted\"\" Co\",\"two\nlines\"\n\
                    MA-M,C85CE27,Plain,x";
        let r = csv_records(text);
        assert_eq!(r.len(), 4);
        assert_eq!(r[1], ["MA-L", "A483E7", "Apple, Inc.", "1 Infinite Loop"]);
        assert_eq!(r[2][2], "The \"Quoted\" Co");
        assert_eq!(r[2][3], "two\nlines");
        assert_eq!(r[3], ["MA-M", "C85CE27", "Plain", "x"]);
        assert_eq!(normalise("  Acme\tRadio\n Ltd. "), "Acme Radio Ltd.");
    }

    /// **The snapshot is what its header says it is.** Every source is named
    /// with its checksum and row count, the rows add up to those counts, and
    /// the date is a date. A snapshot edited by hand, or cut short, fails
    /// here rather than answering lookups from a partial listing.
    #[test]
    fn the_snapshot_is_what_its_header_says() {
        let fetched = fetched();
        assert!(
            fetched.len() == 10 && fetched.as_bytes()[4] == b'-' && fetched.as_bytes()[7] == b'-',
            "{fetched:?}"
        );
        let mut declared = 0usize;
        let mut sources = 0;
        for line in SNAPSHOT.lines().filter(|l| l.starts_with("# source ")) {
            let words: Vec<&str> = line.split_whitespace().collect();
            let rows = words.iter().position(|w| *w == "rows").unwrap();
            declared += words[rows + 1].parse::<usize>().unwrap();
            let sha = words.iter().position(|w| *w == "sha256").unwrap();
            assert_eq!(words[sha + 1].len(), 64, "{line}");
            sources += 1;
        }
        assert_eq!(sources, SOURCES.len());
        let rows = SNAPSHOT
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .count();
        assert_eq!(rows, declared, "rows in the file against rows declared");
        let parsed: usize = table().blocks.iter().map(Vec::len).sum();
        assert_eq!(parsed, rows, "every row parsed into a block");
        assert!(rows > 50_000, "{rows}: not the whole listing");
    }

    /// Names are stored normalised: no tab, no line break, no space at an end,
    /// no run of spaces.
    #[test]
    fn every_name_is_stored_normalised() {
        for list in &table().blocks {
            for (prefix, name) in list {
                assert!(!name.is_empty(), "{prefix:x}");
                assert_eq!(*name, normalise(name), "{prefix:x}");
            }
        }
    }

    fn addr(hex: &str) -> [u8; 6] {
        let digits: String = hex.chars().filter(|c| c.is_ascii_hexdigit()).collect();
        let padded = format!("{digits:0<12}");
        let mut out = [0u8; 6];
        for (i, b) in out.iter_mut().enumerate() {
            *b = u8::from_str_radix(&padded[2 * i..2 * i + 2], 16).unwrap();
        }
        out
    }

    /// Lookups the listing itself settles, one per block size and one per
    /// shape of answer, each checked against the downloaded CSVs when the
    /// snapshot was built.
    #[test]
    fn each_block_size_resolves_to_its_own_registrant() {
        let listed = |a: &str| match registrant(addr(a)) {
            Registrant::Listed(names) => names,
            other => panic!("{a}: {other:?}"),
        };
        // MA-L, 24 bits. The address the census fixtures have used all along.
        assert_eq!(listed("a4:83:e7:1c:09:be"), ["Apple, Inc."]);
        // MA-M, 28 bits, inside an MA-L registered to the registry itself:
        // stopping at 24 bits would answer "IEEE Registration Authority".
        assert_eq!(
            listed("c8:5c:e2:70:00:00"),
            ["SYNERGY SYSTEMS AND SOLUTIONS"]
        );
        // The one 28-bit sub-block of that MA-L nobody holds falls back to it.
        assert_eq!(listed("c8:5c:e2:f0:00:00"), ["IEEE Registration Authority"]);
        // MA-S and IAB, 36 bits, the same way.
        assert_eq!(
            listed("8c:1f:64:af:a0:00"),
            ["DATA ELECTRONIC DEVICES, INC"]
        );
        assert_eq!(listed("40:d8:55:0d:70:00"), ["Avant Technologies"]);
    }

    #[test]
    fn a_hidden_block_is_private_and_a_shared_one_names_everyone() {
        assert_eq!(registrant(addr("e4:f1:4c:00:00:01")), Registrant::Private);
        // Three organisations under one legacy block, in the listing's order,
        // and none chosen over the others.
        match registrant(addr("08:00:30:12:34:56")) {
            Registrant::Listed(names) => {
                assert_eq!(names.len(), 3, "{names:?}");
                assert!(names.contains(&"CERN"), "{names:?}");
            }
            other => panic!("{other:?}"),
        }
    }

    /// A block nobody holds is not listed, and says so rather than borrowing
    /// the nearest neighbour's name. `02:00:00` is locally administered and
    /// unassigned in the snapshot.
    #[test]
    fn an_unlisted_block_is_not_given_a_neighbours_name() {
        assert_eq!(registrant(addr("02:00:00:00:00:00")), Registrant::NotListed);
    }
}
