// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 MusiThang <viktor.laszlo92@protonmail.com>

//! Names the Bluetooth SIG has assigned to numbers a device sends: company
//! identifiers and 16-bit service UUIDs, as a dated snapshot of the SIG's
//! public Assigned Numbers registry compiled into the binary
//! (net-ux-polish-plan 5.2.b).
//!
//! **Assigned to, not made by**, as with the IEEE listing
//! (`signal::net::vendor`): a company identifier in manufacturer data names
//! whoever the SIG assigned that number to, which is the company whose data
//! format the octets follow, not necessarily who built the device. The label
//! that shows it says "company", never "maker".
//!
//! **A number the snapshot does not list stays a number** (rule 2): assigned
//! since the snapshot, or never assigned, and either way no neighbour's name
//! is borrowed for it.
//!
//! **Dated** (rule 4): [`fetched`] is the day the registry was read. The
//! snapshot is regenerated by `packaging/update-sig.sh`, which downloads the
//! two YAML files and runs `regenerate_the_sig_snapshot` below, so the file in
//! the tree is always this module's own parser's output and never an edit by
//! hand (rule 7). Redistribution is Viktor's decision of 2026-09-19
//! (`dev_docs/net-ux-polish-plan.md` 1.6.d), on the same footing as the IEEE
//! listing.

use std::sync::OnceLock;

/// The snapshot: a `#` header, then `C<TAB>XXXX<TAB>NAME` for a company and
/// `S<TAB>XXXX<TAB>NAME` for a 16-bit service UUID, the number in hex.
const SNAPSHOT: &str = include_str!("sig_numbers.tsv");

struct Table {
    companies: Vec<(u16, &'static str)>,
    services: Vec<(u16, &'static str)>,
    fetched: &'static str,
}

fn table() -> &'static Table {
    static TABLE: OnceLock<Table> = OnceLock::new();
    TABLE.get_or_init(|| parse(SNAPSHOT))
}

fn parse(text: &'static str) -> Table {
    let mut t = Table {
        companies: Vec::new(),
        services: Vec::new(),
        fetched: "",
    };
    for line in text.lines() {
        if let Some(rest) = line.strip_prefix("# fetched ") {
            t.fetched = rest.trim();
            continue;
        }
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        let mut fields = line.splitn(3, '\t');
        let (Some(kind), Some(hex), Some(name)) = (fields.next(), fields.next(), fields.next())
        else {
            continue;
        };
        let Ok(number) = u16::from_str_radix(hex, 16) else {
            continue;
        };
        match kind {
            "C" => t.companies.push((number, name)),
            "S" => t.services.push((number, name)),
            _ => {}
        }
    }
    t.companies.sort_by_key(|(n, _)| *n);
    t.services.sort_by_key(|(n, _)| *n);
    t
}

fn lookup(rows: &[(u16, &'static str)], number: u16) -> Option<&'static str> {
    rows.binary_search_by_key(&number, |(n, _)| *n)
        .ok()
        .map(|i| rows[i].1)
}

/// The company the SIG assigned `id` to, or `None` where the snapshot does
/// not list it.
pub fn company(id: u16) -> Option<&'static str> {
    lookup(&table().companies, id)
}

/// The SIG's name for a 16-bit service UUID, or `None` where the snapshot does
/// not list it.
// Drawn by the packet detail view (net-ux-polish-plan 5.4); goes with it.
#[cfg_attr(not(test), allow(dead_code))]
pub fn service16(uuid: u16) -> Option<&'static str> {
    lookup(&table().services, uuid)
}

/// The day the snapshot was read from the registry, `YYYY-MM-DD`.
pub fn fetched() -> &'static str {
    table().fetched
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The files the generator reads, and the key naming each entry's number.
    const SOURCES: [(&str, &str, &str); 2] = [
        ("company_identifiers.yaml", "value", "C"),
        ("service_uuids.yaml", "uuid", "S"),
    ];

    /// A YAML scalar as the registry writes a name: single-quoted with `''`
    /// for a quote, double-quoted, or bare.
    fn unquote(raw: &str) -> String {
        let raw = raw.trim();
        let name = if let Some(inner) = raw.strip_prefix('\'').and_then(|r| r.strip_suffix('\'')) {
            inner.replace("''", "'")
        } else if let Some(inner) = raw.strip_prefix('"').and_then(|r| r.strip_suffix('"')) {
            inner.replace("\\\"", "\"")
        } else {
            raw.to_string()
        };
        name.split_whitespace().collect::<Vec<_>>().join(" ")
    }

    /// `(number, name)` from one registry file: each `- <key>: 0xXXXX`
    /// followed by its `name:`.
    fn entries(text: &str, key: &str) -> Vec<(u16, String)> {
        let marker = format!("- {key}:");
        let mut out = Vec::new();
        let mut pending: Option<u16> = None;
        for line in text.lines() {
            let line = line.trim();
            if let Some(hex) = line.strip_prefix(&marker) {
                let hex = hex.trim().trim_start_matches("0x").trim_start_matches("0X");
                pending =
                    Some(u16::from_str_radix(hex, 16).unwrap_or_else(|e| panic!("{line}: {e}")));
            } else if let (Some(n), Some(name)) = (pending, line.strip_prefix("name:")) {
                out.push((n, unquote(name)));
                pending = None;
            }
        }
        out
    }

    /// Regenerate `sig_numbers.tsv` from a download: run by
    /// `packaging/update-sig.sh`, never by `cargo test`.
    #[test]
    #[ignore]
    fn regenerate_the_sig_snapshot() {
        let dir = std::path::PathBuf::from(
            std::env::var("SDRTOP_SIG_DIR").expect("SDRTOP_SIG_DIR names the download"),
        );
        let read =
            |f: &str| std::fs::read_to_string(dir.join(f)).unwrap_or_else(|e| panic!("{f}: {e}"));
        let fetched = read("FETCHED").trim().to_string();
        let sums = read("SHA256SUMS");
        let mut header = vec![
            "# Bluetooth SIG Assigned Numbers, as sdrtop's signal::ble::assigned".to_string(),
            "# reads them. Generated by packaging/update-sig.sh; do not edit by".to_string(),
            "# hand. KIND<TAB>NUMBER<TAB>NAME: C a company identifier, S a 16-bit".to_string(),
            "# service UUID, the number in hex.".to_string(),
            format!("# fetched {fetched}"),
        ];
        let mut rows = Vec::new();
        for (file, key, kind) in SOURCES {
            let found = entries(&read(file), key);
            assert!(!found.is_empty(), "{file}: no entries");
            let sha = sums
                .lines()
                .find(|l| l.ends_with(file))
                .and_then(|l| l.split_whitespace().next())
                .unwrap_or_else(|| panic!("{file}: no checksum"));
            header.push(format!(
                "# source https://bitbucket.org/bluetooth-SIG/public {file} rows {} sha256 {sha}",
                found.len()
            ));
            for (n, name) in found {
                rows.push(format!("{kind}\t{n:04X}\t{name}"));
            }
        }
        rows.sort();
        let mut out = header.join("\n");
        out.push('\n');
        for row in rows {
            out.push_str(&row);
            out.push('\n');
        }
        let path =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src/signal/ble/sig_numbers.tsv");
        std::fs::write(&path, out).unwrap();
    }

    /// The registry's quoting, read back: an apostrophe inside single quotes
    /// doubled, one inside double quotes as it is, a bare name, and stray
    /// whitespace folded.
    #[test]
    fn the_registry_s_quoting_is_read_as_it_is_written() {
        let text = "company_identifiers:\n\n  - value: 0x004C\n    name: 'Apple, Inc.'\n\n  - value: 0x0001\n    name: 'O''Brien  Ltd'\n  - value: 0x1234\n    name: \"Xi'an Co\"\n";
        assert_eq!(
            entries(text, "value"),
            [
                (0x004C, "Apple, Inc.".to_string()),
                (0x0001, "O'Brien Ltd".to_string()),
                (0x1234, "Xi'an Co".to_string()),
            ]
        );
        let services =
            " - uuid: 0x180F\n   name: Battery\n   id: org.bluetooth.service.battery_service\n";
        assert_eq!(entries(services, "uuid"), [(0x180F, "Battery".to_string())]);
    }

    /// **The snapshot in the tree is the one the header describes**: as
    /// many rows of each kind as the header says were read, and a date.
    #[test]
    fn the_snapshot_holds_what_its_header_says() {
        let t = table();
        assert_eq!(fetched().len(), 10, "{:?}", fetched());
        let declared = |file: &str| -> usize {
            SNAPSHOT
                .lines()
                .find(|l| l.starts_with("# source") && l.contains(file))
                .and_then(|l| l.split(" rows ").nth(1))
                .and_then(|r| r.split_whitespace().next())
                .and_then(|n| n.parse().ok())
                .unwrap_or_else(|| panic!("{file}: no row count"))
        };
        assert_eq!(t.companies.len(), declared("company_identifiers.yaml"));
        assert_eq!(t.services.len(), declared("service_uuids.yaml"));
    }

    /// The real packet's company (`ad`'s test), a service every phone
    /// advertises, and numbers the registry does not list staying numbers.
    #[test]
    fn known_numbers_are_named_and_unknown_ones_are_not() {
        assert_eq!(company(0x004C), Some("Apple, Inc."));
        assert_eq!(service16(0x180F), Some("Battery"));
        assert_eq!(company(0xFFFF), None);
        assert_eq!(service16(0x0001), None);
    }
}
