#!/bin/sh

# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 MusiThang <viktor.laszlo92@protonmail.com>

# Refresh the embedded IEEE address-block listing.
#
#   packaging/update-oui.sh
#
# Downloads the IEEE Registration Authority's four public listings (MA-L,
# MA-M, MA-S, IAB), records their checksums and today's date, and hands them
# to the generator in src/signal/net/vendor.rs, which rewrites
# src/signal/net/ieee_oui.tsv. The snapshot is only ever this script's output:
# a file generated by the code that reads it is one that cannot disagree with
# it (POLICY rule 7).
#
# The IEEE's server rejects curl's default User-Agent with a "Request
# Rejected" page and a 418, so this sends a browser's, and checks every file
# starts with the IEEE's CSV header rather than trusting the status alone.
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BASE="https://standards-oui.ieee.org"
AGENT="Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"

DIR=$(mktemp -d)
trap 'rm -rf "$DIR"' EXIT

for path in oui/oui.csv oui28/mam.csv oui36/oui36.csv iab/iab.csv; do
    file=$(basename "$path")
    curl --fail --silent --show-error --location \
        --user-agent "$AGENT" --output "$DIR/$file" "$BASE/$path"
    head -c 9 "$DIR/$file" | grep -q '^Registry' || {
        echo "update-oui.sh: $file is not the IEEE's listing" >&2
        exit 1
    }
    # One request at a time, a second apart: this is someone else's server.
    sleep 1
done

(cd "$DIR" && sha256sum oui.csv mam.csv oui36.csv iab.csv > SHA256SUMS)
date -u +%Y-%m-%d > "$DIR/FETCHED"

SDRTOP_IEEE_DIR="$DIR" cargo test --locked --manifest-path "$ROOT/Cargo.toml" \
    -- --ignored --exact signal::net::vendor::tests::regenerate_the_oui_snapshot

echo "update-oui.sh: src/signal/net/ieee_oui.tsv rewritten from the listing of $(cat "$DIR/FETCHED")"
