#!/bin/sh

# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 MusiThang <viktor.laszlo92@protonmail.com>

# Refresh the embedded Bluetooth SIG Assigned Numbers snapshot.
#
#   packaging/update-sig.sh
#
# Downloads the SIG's public company identifier and 16-bit service UUID
# registries, records their checksums and today's date, and hands them to the
# generator in src/signal/ble/assigned.rs, which rewrites
# src/signal/ble/sig_numbers.tsv. The snapshot is only ever this script's
# output: a file generated by the code that reads it is one that cannot
# disagree with it (POLICY rule 7). The same shape as update-oui.sh.
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BASE="https://bitbucket.org/bluetooth-SIG/public/raw/main/assigned_numbers"

DIR=$(mktemp -d)
trap 'rm -rf "$DIR"' EXIT

fetch() {
    path=$1
    top=$2
    file=$(basename "$path")
    curl --fail --silent --show-error --location --output "$DIR/$file" "$BASE/$path"
    # The registry's own top-level key, not an error page that happened to
    # come back with a 200.
    grep -q "^$top:" "$DIR/$file" || {
        echo "update-sig.sh: $file is not the SIG's registry" >&2
        exit 1
    }
    # One request at a time, a second apart: this is someone else's server.
    sleep 1
}

fetch company_identifiers/company_identifiers.yaml company_identifiers
fetch uuids/service_uuids.yaml uuids

(cd "$DIR" && sha256sum company_identifiers.yaml service_uuids.yaml > SHA256SUMS)
date -u +%Y-%m-%d > "$DIR/FETCHED"

SDRTOP_SIG_DIR="$DIR" cargo test --locked --manifest-path "$ROOT/Cargo.toml" \
    -- --ignored --exact signal::ble::assigned::tests::regenerate_the_sig_snapshot

echo "update-sig.sh: src/signal/ble/sig_numbers.tsv rewritten from the registry of $(cat "$DIR/FETCHED")"
